from django.urls import path, include
from .views import (
    authView,
    bassin_add,
    bassin_delete,
    bassin_edit,
    bassin_pdf,
    bassins,
    fournisseur_add,
    fournisseur_delete,
    fournisseur_edit,
    fournisseurs,
    home,
    logout,
    materiau_add,
    materiau_delete,
    materiau_edit,
    materiaux,
    projet_add,
    delete_projet,
    projet_edit,
    projets,
    volume_add,
    volume_delete,
    volume_edit,
    volumes,
)

urlpatterns = [
    path("", home, name="home"),
    path('projets/', projets, name='projets'),
    path('projets/add/', projet_add, name='projet_add'),  # Assurez-vous que cette ligne est présente
    path('projets/edit/<int:pk>/', projet_edit, name='projet_edit'),
   path('projets/delete/<int:pk>/', delete_projet, name='projet_delete'),
    path('bassins/', bassins, name='bassins'),
    path('bassins/add/', bassin_add, name='bassin_add'),
    path('bassins/edit/<int:pk>/', bassin_edit, name='bassin_edit'),
    path('bassins/delete/<int:pk>/', bassin_delete, name='bassin_delete'),
    path('fournisseurs/', fournisseurs, name='fournisseurs'),
    path('fournisseurs/add/', fournisseur_add, name='fournisseur_add'),
    path('fournisseurs/edit/<int:pk>/', fournisseur_edit, name='fournisseur_edit'),
    path('fournisseurs/delete/<int:pk>/', fournisseur_delete, name='fournisseur_delete'),
    path('materiaux/', materiaux, name='materiaux'),
    path('materiaux/add/', materiau_add, name='materiau_add'),
    path('materiaux/edit/<int:pk>/', materiau_edit, name='materiau_edit'),
    path('materiaux/delete/<int:pk>/', materiau_delete, name='materiau_delete'),
    path('volumes/', volumes, name='volumes'),
    path('volumes/add/', volume_add, name='volume_add'),
    path('volumes/edit/<int:pk>/', volume_edit, name='volume_edit'),
    path('volumes/delete/<int:pk>/', volume_delete, name='volume_delete'),
    path("logout/", logout, name="logout"),
    path("signup/", authView, name="authView"),
    path("accounts/", include("django.contrib.auth.urls")),
    path('bassin/pdf/', bassin_pdf, name='bassin_pdf'),
]