# Generated by Django 5.2 on 2025-04-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BassinSalins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_bassin', models.IntegerField(blank=True, null=True)),
                ('Id_projet', models.IntegerField(blank=True, null=True)),
                ('Id_volume', models.IntegerField(blank=True, null=True)),
                ('Surface_bassin', models.IntegerField(blank=True, null=True)),
                ('Capacite', models.IntegerField(blank=True, null=True)),
                ('Date_construction', models.CharField(blank=True, max_length=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_fournisseur', models.IntegerField(blank=True, null=True)),
                ('Nom_fournisseur', models.CharField(blank=True, max_length=30, null=True)),
                ('Adr_fournisseur', models.CharField(blank=True, max_length=37, null=True)),
                ('Tel_fournisseur', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materiaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_materiau', models.IntegerField(blank=True, null=True)),
                ('Nom_materiau', models.CharField(blank=True, max_length=50, null=True)),
                ('Unite', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantite_stock', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_projet', models.IntegerField(blank=True, null=True)),
                ('Nom_projet', models.CharField(blank=True, max_length=50, null=True)),
                ('Lieu', models.CharField(blank=True, max_length=30, null=True)),
                ('Date_debut', models.CharField(blank=True, max_length=19, null=True)),
                ('Date_fin', models.CharField(blank=True, max_length=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_volume', models.IntegerField(blank=True, null=True)),
                ('Volume_disponible', models.IntegerField(blank=True, null=True)),
                ('Unite', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
