# Generated by Django 5.2 on 2025-04-11 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_projet_date_debut_alter_projet_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaux',
            name='Id_projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.projet'),
        ),
        migrations.AlterField(
            model_name='fournisseurs',
            name='Adr_fournisseur',
            field=models.CharField(default='Non spécifiée', max_length=37),
        ),
        migrations.AlterField(
            model_name='fournisseurs',
            name='Nom_fournisseur',
            field=models.CharField(default='Non spécifiée', max_length=30),
        ),
        migrations.AlterField(
            model_name='materiaux',
            name='Nom_materiau',
            field=models.CharField(default='Non spécifiée', max_length=50),
        ),
        migrations.AlterField(
            model_name='materiaux',
            name='Unite',
            field=models.CharField(default='Non spécifiée', max_length=50),
        ),
    ]
