# Generated by Django 5.2 on 2025-04-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_materiaux_id_projet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='Lieu',
        ),
        migrations.AddField(
            model_name='projet',
            name='Description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='Dure',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
