# Generated by Django 5.2 on 2025-04-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_projet_lieu_projet_description_projet_dure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='Date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projet',
            name='Date_fin',
            field=models.DateField(),
        ),
    ]
