# Generated by Django 5.2 on 2025-04-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_materiaux_id_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volumes',
            name='Unite',
        ),
        migrations.AddField(
            model_name='volumes',
            name='date_mesure',
            field=models.DateField(blank=True, null=True),
        ),
    ]
