# Generated by Django 5.2 on 2025-04-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_volumes_unite_volumes_date_mesure'),
    ]

    operations = [
        migrations.AddField(
            model_name='bassinsalins',
            name='Nb_bassin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bassinsalins',
            name='Sel_produit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
