# Generated by Django 5.2 on 2025-04-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_bassinsalins_nb_bassin_bassinsalins_sel_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bassinsalins',
            name='Date_construction',
            field=models.DateField(blank=True, null=True),
        ),
    ]
